[versions]
junit5 = "6.0.1"

[libraries]
androidx-annotation = { group = "androidx.annotation", name = "annotation", version = "1.9.1" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
hamcrest-library = { group = "org.hamcrest", name = "hamcrest-library", version = "3.0" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit5" }
tazkiyatech-test-utils = { group = "com.tazkiyatech", name = "android-test-utils", version = "3.0.0" }
test-orchestrator = { group = "androidx.test", name = "orchestrator", version = "1.6.1" }

[plugins]
android-library = { id = "com.android.library", version = "8.13.0" }
benmanes-versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.2.21" }
